Config = {}

Config.Products = {
    ["bagstore"] = {
       [1] = {
            name = "smallbackpack",
            price = 20000,
            amount = 100,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "mediumbackpack",
            price = 30000,
            amount = 100,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "largebackpack",
            price = 40000,
            amount = 100,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "mala_roupas",
            price = 1999,
            amount = 10,
            info = {},
            type = "item",
            slot = 4,
        },
        
    },  
--     ["parachuteshop"] = {
--     [1] = {
--         name = "binoculars",
--         price = 50,
--         amount = 50,
--         info = {},
--         type = "item",
--         slot = 1,
--     },
--     [2] = {
--         name = "diving_gear",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 2,
--     },
--     [3] = {
--         name = "rainbow-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [4] = {
--         name = "red-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [5] = {
--         name = "seaside-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [6] = {
--         name = "widow-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [7] = {
--         name = "patriot-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [8] = {
--         name = "blue-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [9] = {
--         name = "black-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [10] = {
--         name = "hornet-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [11] = {
--         name = "airforce-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [12] = {
--         name = "desert-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [13] = {
--         name = "shadow-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [14] = {
--         name = "highalt-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [15] = {
--         name = "airborn-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
--     [16] = {
--         name = "sunrise-parachute",
--         price = 4999,
--         amount = 10,
--         info = {},
--         type = "item",
--         slot = 3,
--     },
-- },
}

Config.Locations = {
    
    ["bagstore"] = {
        ["label"] = "Backpack Store",
        ["coords"] = vector4(401.71, 97.46, 101.52, 348.68),
        ["ped"] = 'u_m_y_gabriel',
        ["radius"] = 2,
        ["targetIcon"] = "a-solid fa-backpack",
        ["targetLabel"] = "OPEN BACKPACK STORE",
        ["products"] = Config.Products["bagstore"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },
    -- ["parachuteshop"] = {
    --     ["label"] = "Tinted Parachute Store",
    --     ["coords"] = vector4(1740.21, 3290.82, 41.11),
    --     ["ped"] = 'u_m_y_gabriel',
    --     ["radius"] = 2,
    --     ["targetIcon"] = "a-solid fa-backpack",
    --     ["targetLabel"] = "OPEN Tinted Parachute Store",
    --     ["products"] = Config.Products["parachuteshop"],
    --     ["showblip"] = true,
    --     ["blipsprite"] = 94,
    --     ["blipcolor"] = 0
    -- },

}
