var tableauQuestion = [
    {   question : "How old do you need to be to drive a gearless two wheeler?",
        propositionA : "16 years",
        propositionB : "18 years",
        propositionC : "20 years",
        propositionD : "22 years",
        reponse : "A"},

    {   question : "What should you do when you see a traffic sign of a school nearby?",
        propositionA : "Stop the vehicle",
        propositionB : "Press the horn and proceed at the same speed",
        propositionC : "Slow down and proceed carefully",
        propositionD : "Check your mirrors",
        reponse : "C"},

    {   question : "What needs to be kept in mind before overtaking a vehicle?",
        propositionA : "Clear visibility of the road ahead and safe possibility of overtaking",
        propositionB : "The road is not safe",
        propositionC : "40",
        propositionD : "45",
        reponse : "A"},

  {   question : " If a driver sees the sign for - slippery road ahead, he/she must:",
        propositionA : "Drive faster",
        propositionB : "Check your blind spots",
        propositionC : "Press the horn and proceed at the same speed",
        propositionD : "Change gear and reduce speed",
        reponse : "D"},

  {   question : "Overspeeding is :",
        propositionA : "Not an offence and can be neglected",
        propositionB : "Is an offence, but no charges are pressed against you",
        propositionC : "An offence that could lead to your driving licence being cancelled or suspended",
        propositionD : "All of the above",
        reponse : "C"},

  {   question : "What should be your course of action in case you see a vehicle that has met with an accident with injured passengers inside?",
        propositionA : "Stop your vehicle and report the matter to the nearest police station",
        propositionB : "Take the vehicle to the closest police station and report the accident",
        propositionC : "Overtake the vehicle from the left side of the vehicle ahead",
        propositionD : "Take measures to secure medical attention to those injured and report the accident to the closest police station within a period of 24 hours",
        reponse : "D"},

  {   question : "A pedestrian has a do not cross signal, what do you do?",
        propositionA : "You let them pass",
        propositionB : "You observe before continuing",
        propositionC : "You wave to tell them to cross",
        propositionD : "You continue because your traffic light is green",
        reponse : "D"},

  {   question : "What is allowed when passing another vehicle",
        propositionA : "You follow it closely to pass it faster",
        propositionB : "You pass it without leaving the roadway",
        propositionC : "You drive on the opposite side of the road to pass",
        propositionD : "You exceed the speed limit to pass them",
        reponse : "C"},

  {   question : "Where is the use of horns prohibited?",
        propositionA : "Near Police Station",
        propositionB : "Near Schools and Colleges",
        propositionC : "Near Stores and Public Places",
        propositionD : "Near Hospitals and Courts of Law",
        reponse : "D"},

  {   question : "Fog lamps should be used when:",
        propositionA : "At night",
        propositionB : "When the vehicle opposite is not using the dim light",
        propositionC : "When other drivers available",
        propositionD : "There is mist",
        reponse : "D"},
]
