
----------------------------------------------------------------------- W A L M A R T -------------------------------------------------------------------------

local blip1 = AddBlipForCoord(-555.82, -624.09, 34.68) 
SetBlipSprite(blip1, 52)  
SetBlipScale(blip1, 0.55) 
SetBlipColour(blip1, 5) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Walmart')
EndTextCommandSetBlipName(blip1)

--------------------------------------------------------------------- C L O T H I N G -------------------------------------------------------------------------

local blip1 = AddBlipForCoord(1693.32, 4823.48, 41.06) 
SetBlipSprite(blip1, 73)  
SetBlipScale(blip1, 0.55) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Clothing Store ')
EndTextCommandSetBlipName(blip1)

local blip1 = AddBlipForCoord(4.254, 6512.813, 30.877) 
SetBlipSprite(blip1, 73)  
SetBlipScale(blip1, 0.6) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Clothing Store ')
EndTextCommandSetBlipName(blip1)

local blip1 = AddBlipForCoord(615.180, 2762.933, 41.088) 
SetBlipSprite(blip1, 73)  
SetBlipScale(blip1, 0.6) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Clothing Store ')
EndTextCommandSetBlipName(blip1)

local blip1 = AddBlipForCoord(1196.785, 2709.558, 37.222) 
SetBlipSprite(blip1, 73)  
SetBlipScale(blip1, 0.6) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Clothing Store ')
EndTextCommandSetBlipName(blip1)

local blip1 = AddBlipForCoord(-3171.453, 1043.857, 19.863) 
SetBlipSprite(blip1, 73)  
SetBlipScale(blip1, 0.6) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Clothing Store ')
EndTextCommandSetBlipName(blip1)

local blip1 = AddBlipForCoord(-1100.959, 2710.211, 18.107) 
SetBlipSprite(blip1, 73)  
SetBlipScale(blip1, 0.6) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Clothing Store ')
EndTextCommandSetBlipName(blip1)

--------------------------------------------------------------------- B A R B E R -------------------------------------------------------------------------

local blip1 = AddBlipForCoord(136.8, -1708.4, 28.3) 
SetBlipSprite(blip1, 71)  
SetBlipScale(blip1, 0.6) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Barber Shop')
EndTextCommandSetBlipName(blip1)

local blip1 = AddBlipForCoord(-1282.6, -1116.8, 6.0) 
SetBlipSprite(blip1, 71)  
SetBlipScale(blip1, 0.6) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Barber Shop')
EndTextCommandSetBlipName(blip1)

local blip1 = AddBlipForCoord(1931.5, 3729.7, 31.8) 
SetBlipSprite(blip1, 71)  
SetBlipScale(blip1, 0.6) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Barber Shop')
EndTextCommandSetBlipName(blip1)

local blip1 = AddBlipForCoord(-32.9, -152.3, 56.1) 
SetBlipSprite(blip1, 71)  
SetBlipScale(blip1, 0.6) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Barber Shop')
EndTextCommandSetBlipName(blip1)

local blip1 = AddBlipForCoord(-278.1, 6228.5, 30.7) 
SetBlipSprite(blip1, 71)  
SetBlipScale(blip1, 0.6) 
SetBlipColour(blip1, 0) 
SetBlipAsShortRange(blip1, true)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString('Barber Shop')
EndTextCommandSetBlipName(blip1)
