QBShared = QBShared or {}
QBShared.VehicleHashes = {}

QBShared.Vehicles = {
	
	--// Exclusive Vehicles
	['ie'] = {
		['name'] = 'IE',
		['brand'] = 'Apollo',
		['model'] = 'ie',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `ie`,
		['shop'] = 'edm',
	},
    ['rmodbacalar'] = {
		['name'] = 'Bentley Bacalar',
		['brand'] = 'Bentley',
		['model'] = 'rmodbacalar',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `rmodbacalar`,
		['shop'] = 'edm',
	},
	['rmodmi8lb'] = {
		['name'] = 'BMW i8',
		['brand'] = 'BMW',
		['model'] = 'rmodmi8lb',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `rmodmi8lb`,
		['shop'] = 'edm',
	},
	['rmodbugatti'] = {
		['name'] = 'Bugatti La Voiture Noire',
		['brand'] = 'Bugatti',
		['model'] = 'rmodbugatti',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `rmodbugatti`,
		['shop'] = 'edm',
	},
	['vsgran'] = {
		['name'] = 'Lamborghini V12 Vision GT',
		['brand'] = 'Lamborghini',
		['model'] = 'vsgran',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `vsgran`,
		['shop'] = 'edm',
	},
	['furai'] = {
		['name'] = 'Mazda Furai',
		['brand'] = 'Mazda',
		['model'] = 'furai',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `furai`,
		['shop'] = 'edm',
	},
	['zn20'] = {
		['name'] = 'Zenvo',
		['brand'] = 'Zenvo',
		['model'] = 'zn20',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `zn20`,
		['shop'] = 'edm',
	},
	['bolide'] = {
		['name'] = 'Buggati Bolide',
		['brand'] = 'Buggati',
		['model'] = 'bolide',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `bolide`,
		['shop'] = 'edm',
	},
	['demon'] = {
		['name'] = 'Dodge Demon',
		['brand'] = 'Dodge',
		['model'] = 'demon',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `demon`,
		['shop'] = 'edm',
	},
	['ocnlamtmc'] = {
		['name'] = 'Terzo',
		['brand'] = 'Lamborghini',
		['model'] = 'ocnlamtmc',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `ocnlamtmc`,
		['shop'] = 'edm',
	},
	['p1'] = {
		['name'] = 'MclarenP 1',
		['brand'] = 'Mclaren',
		['model'] = 'p1',
		['price'] = 100000000,
		['category'] = 'exclusive',
		['hash'] = `p1`,
		['shop'] = 'edm',
	},
	
	--// Animated Vehicles
	['VictorHirot'] = {
		['name'] = 'Victor Hirot',
		['brand'] = 'AstonMartin',
		['model'] = 'VictorHirot',
		['price'] = 100000000,
		['category'] = 'animated',
		['hash'] = `VictorHirot`,
		['shop'] = 'edm',
	},
	['svjroadster20'] = {
		['name'] = 'SVJ Roadstar',
		['brand'] = 'Lamborghini',
		['model'] = 'svjroadster20',
		['price'] = 100000000,
		['category'] = 'animated',
		['hash'] = `svjroadster20`,
		['shop'] = 'edm',
	},
	['ocnetrongt'] = {
		['name'] = 'Audi Etron GT',
		['brand'] = 'Audi',
		['model'] = 'ocnetrongt',
		['price'] = 100000000,
		['category'] = 'animated',
		['hash'] = `ocnetrongt`,
		['shop'] = 'edm',
	},
	['m4comp'] = {
		['name'] = 'Bmw M4 G82',
		['brand'] = 'BMW',
		['model'] = 'm4comp',
		['price'] = 100000000,
		['category'] = 'animated',
		['hash'] = `m4comp`,
		['shop'] = 'edm',
	},
	['sian'] = {
		['name'] = 'Sian',
		['brand'] = 'Lamborghini',
		['model'] = 'sian',
		['price'] = 100000000,
		['category'] = 'animated',
		['hash'] = `sian`,
		['shop'] = 'edm',
	},

	--// Limited Edition Vehicles
	['db11'] = {
		['name'] = 'Aston Martin DB11',
		['brand'] = 'Aston Martin',
		['model'] = 'db11',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `db11`,
		['shop'] = 'edm',
	},
	['rs7r'] = {
		['name'] = 'Audi RS7 R',
		['brand'] = 'Audi',
		['model'] = 'rs7r',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `rs7r`,
		['shop'] = 'edm',
	},
	['rmodm5e34'] = {
		['name'] = 'Bmw M5 Classic',
		['brand'] = 'BMW',
		['model'] = 'rmodm5e34',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `rmodm5e34`,
		['shop'] = 'edm',
	},
	['bmwm8'] = {
		['name'] = 'BMW M8',
		['brand'] = 'BMW',
		['model'] = 'bmwm8',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `bmwm8`,
		['shop'] = 'edm',
	},
	['rmode63s'] = {
		['name'] = 'Brabus C Class ',
		['brand'] = 'Brabus',
		['model'] = 'rmode63s',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `rmode63s`,
		['shop'] = 'edm',
	},
	['brabus700'] = {
		['name'] = 'Brabus700 6x6',
		['brand'] = 'Brabus',
		['model'] = 'brabus700',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `brabus700`,
		['shop'] = 'edm',
	},
	['21camaro'] = {
		['name'] = 'Camaro',
		['brand'] = 'Chevrolet',
		['model'] = '21camaro',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `21camaro`,
		['shop'] = 'edm',
	},
	['rmodf12tdf'] = {
		['name'] = 'Ferrari F12',
		['brand'] = 'Ferrari',
		['model'] = 'rmodf12tdf',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `rmodf12tdf`,
		['shop'] = 'edm',
	},
	['firecast'] = {
		['name'] = 'Firecast',
		['brand'] = 'Firecast',
		['model'] = 'firecast',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `firecast`,
		['shop'] = 'edm',
	},
	['gt17'] = {
		['name'] = 'Ford GT17',
		['brand'] = 'Ford',
		['model'] = 'gt17',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `gt17`,
		['shop'] = 'edm',
	},
	['foxshelby'] = {
		['name'] = 'Ford Shelby GT500',
		['brand'] = 'Ford',
		['model'] = 'foxshelby',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `foxshelby`,
		['shop'] = 'edm',
	},
	['22g63'] = {
		['name'] = 'G Wagon',
		['brand'] = 'Mercedes',
		['model'] = '22g63',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `22g63`,
		['shop'] = 'edm',
	},
	['ninjah2'] = {
		['name'] = 'Kawasaki H2R',
		['brand'] = 'Kawasaki',
		['model'] = 'ninjah2',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `ninjah2`,
		['shop'] = 'edm',
	},
	['rmodjesko'] = {
		['name'] = 'Jesko',
		['brand'] = 'Koenigsegg',
		['model'] = 'rmodjesko',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `rmodjesko`,
		['shop'] = 'edm',
	},
	['laferrari17'] = {
		['name'] = 'LaFerrari 17',
		['brand'] = 'Ferrari',
		['model'] = 'laferrari17',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `laferrari17`,
		['shop'] = 'edm',
	},
	['rmodlp750'] = {
		['name'] = 'Lamborghini Aventador LP',
		['brand'] = 'Lamborghini',
		['model'] = 'rmodlp750',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `rmodlp750`,
		['shop'] = 'edm',
	},
	['sianr'] = {
		['name'] = 'Sian Roadster',
		['brand'] = 'Lamborghini',
		['model'] = 'sianr',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `sianr`,
		['shop'] = 'edm',
	},
	['mgt'] = {
		['name'] = 'Mustang GT',
		['brand'] = 'Ford',
		['model'] = 'mgt',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `mgt`,
		['shop'] = 'edm',
	},
	['gtr'] = {
		['name'] = 'Nissan GT-R',
		['brand'] = 'Nissan',
		['model'] = 'gtr',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `gtr`,
		['shop'] = 'edm',
	},
	['turs21'] = {
		['name'] = 'Porshe Turns21',
		['brand'] = 'Porshe',
		['model'] = 'turs21',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `turs21`,
		['shop'] = 'edm',
	},
	['wraithb'] = {
		['name'] = 'RollsRoyce Wraith',
		['brand'] = 'RollsRoyce',
		['model'] = 'wraithb',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `wraithb`,
		['shop'] = 'edm',
	},
	['bcr1drag'] = {
		['name'] = 'Yamaha YZF R1',
		['brand'] = 'Yamaha',
		['model'] = 'bcr1drag',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `bcr1drag`,
		['shop'] = 'edm',
	},
	['bmci'] = {
		['name'] = 'BMW M5',
		['brand'] = 'BMW',
		['model'] = 'bmci',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `bmci`,
		['shop'] = 'edm',
	},
	['rmodbentley1'] = {
		['name'] = 'Bentley GT',
		['brand'] = 'Bentley',
		['model'] = 'rmodbentley1',
		['price'] = 100000000,
		['category'] = 'limited',
		['hash'] = `rmodbentley1`,
		['shop'] = 'edm',
	},
	
	--// Non-Limited  Vehicles
	['superleggera'] = {
		['name'] = 'AstonMatin Superleggera',
		['brand'] = 'AstonMatin',
		['model'] = 'superleggera',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `superleggera`,
		['shop'] = 'edm',
	},
	['adr8'] = {
		['name'] = 'Audi R8 Sports Edition',
		['brand'] = 'Audi',
		['model'] = 'adr8',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `adr8`,
		['shop'] = 'edm',
	},
	['rs5'] = {
		['name'] = 'Audi RS5',
		['brand'] = 'Audi',
		['model'] = 'rs5',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `rs5`,
		['shop'] = 'edm',
	},
	['sq72016'] = {
		['name'] = 'Audi SQ7',
		['brand'] = 'Audi',
		['model'] = 'sq72016',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `sq72016`,
		['shop'] = 'edm',
	},
	['bs17'] = {
		['name'] = 'BMW BS17',
		['brand'] = 'BMW',
		['model'] = 'bs17',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `bs17`,
		['shop'] = 'edm',
	},
	['chironps'] = {
		['name'] = 'Chiron Pur',
		['brand'] = 'Buggati',
		['model'] = 'chironps',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `chironps`,
		['shop'] = 'edm',
	},
	['2019zr1c'] = {
		['name'] = 'Corvette ZR1',
		['brand'] = 'Corvette',
		['model'] = '2019zr1c',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `2019zr1c`,
		['shop'] = 'edm',
	},
	['sport'] = {
		['name'] = 'Harley Davidson',
		['brand'] = 'Harley Davidson',
		['model'] = 'sport',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `sport`,
		['shop'] = 'edm',
	},
    ['levante'] = {
		['name'] = 'Maserati Levante',
		['brand'] = 'Maserati',
		['model'] = 'levante',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `levante`,
		['shop'] = 'edm',
	},
    ['fd'] = {
		['name'] = 'Mazda RX7',
		['brand'] = 'Mazda',
		['model'] = 'fd',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `fd`,
		['shop'] = 'edm',
	},
	['720s'] = {
		['name'] = 'McLaren 720s',
		['brand'] = 'Mazda',
		['model'] = '720s',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `720s`,
		['shop'] = 'edm',
	},
    ['rmodgt63'] = {
		['name'] = 'Mercedes AMG GT',
		['brand'] = 'Mercedes',
		['model'] = 'rmodgt63',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `rmodgt63`,
		['shop'] = 'edm',
	},
    ['amggtbs'] = {
		['name'] = 'Mercedes AMG GTBS',
		['brand'] = 'Mercedes',
		['model'] = 'amggtbs',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `amggtbs`,
		['shop'] = 'edm',
	},
	['gle450'] = {
		['name'] = 'Mercedes GLE450',
		['brand'] = 'Mercedes',
		['model'] = 'gle450',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `gle450`,
		['shop'] = 'edm',
	},
    ['evcs65'] = {
		['name'] = 'Mercedes S Class ',
		['brand'] = 'Mercedes',
		['model'] = 'evcs65',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `evcs65`,
		['shop'] = 'edm',
	},
	['evo10'] = {
		['name'] = 'Mitsubishi Lancer Evolution X',
		['brand'] = 'Mitsubishi',
		['model'] = 'evo10',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `evo10`,
		['shop'] = 'edm',
	},
	['13fmb302'] = {
		['name'] = 'Mustang 302',
		['brand'] = 'Ford',
		['model'] = '13fmb302',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `13fmb302`,
		['shop'] = 'edm',
	},
	['pturismo'] = {
		['name'] = 'Porshe Turismo',
		['brand'] = 'Porshe',
		['model'] = 'pturismo',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `pturismo`,
		['shop'] = 'edm',
	},
	['18velar'] = {
		['name'] = 'Range Rover',
		['brand'] = 'RangeRover',
		['model'] = '18velar',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `18velar`,
		['shop'] = 'edm',
	},
    ['skyline'] = {
		['name'] = 'Skyline',
		['brand'] = 'Nissan',
		['model'] = 'skyline',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `skyline`,
		['shop'] = 'edm',
	},
	['rmodsuprapandem'] = {
		['name'] = 'Supra Pandem',
		['brand'] = 'Supra',
		['model'] = 'rmodsuprapandem',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `rmodsuprapandem`,
		['shop'] = 'edm',
	},
	['urus2018'] = {
		['name'] = 'Urus',
		['brand'] = 'Lamborghini',
		['model'] = 'urus2018',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `urus2018`,
		['shop'] = 'edm',
	},
	['r6'] = {
		['name'] = 'Yamaha R6',
		['brand'] = 'Yamaha',
		['model'] = 'r6',
		['price'] = 100000000,
		['category'] = 'nonlimited',
		['hash'] = `r6`,
		['shop'] = 'edm',
	},
	
	---------------------------------------------------------------- E X T R A  -------------------------------------------------------------------
	
	['cls2015'] = {
		['name'] = 'Mercedes S Class ',
		['brand'] = 'Mercedes',
		['model'] = 'cls2015',
		['price'] = 100000000,
		['category'] = 'emergency',
		['hash'] = `cls2015`,
		['shop'] = 'edm',
	},
	['hermes'] = {
		['name'] = 'Hermes',
		['brand'] = 'Albany',
		['model'] = 'hermes',
		['price'] = 450000,
		['category'] = 'emergency',
		['hash'] = `hermes`,
		['shop'] = 'edm',
	},
	['btype3'] = {
		['name'] = 'Roosevelt Valor',
		['brand'] = 'Albany',
		['model'] = 'btype3',
		['price'] = 263000,
		['category'] = 'emergency',
		['hash'] = `btype3`,
		['shop'] = 'edm',
	},
	
	-------------------------------------------------------------------------------- P D M  -------------------------------------------------------------------------------

	--// Motorcycles

	['blazer'] = {
		['name'] = 'Blazer',
		['brand'] = 'Annis',
		['price'] = 20000,
		['category'] = 'motorcycles',
		['model'] = 'blazer',
		['hash'] = `blazer`,
		['shop'] = 'pdm',
	},
	['blazer3'] = {
		['name'] = 'Blazer Hot Rod',
		['brand'] = 'Nagasaki',
		['model'] = 'blazer3',
		['price'] = 30000,
		['category'] = 'motorcycles',
		['hash'] = `blazer3`,
		['shop'] = 'pdm',
	},
	['blazer4'] = {
		['name'] = 'Blazer Sport',
		['brand'] = 'Annis',
		['price'] = 50000,
		['category'] = 'motorcycles',
		['model'] = 'blazer4',
		['hash'] = `blazer4`,
		['shop'] = 'pdm',
	},
	['outlaw'] = {
		['name'] = 'Outlaw',
		['brand'] = 'Nagasaki',
		['model'] = 'outlaw',
		['price'] = 100000,
		['category'] = 'motorcycles',
		['hash'] = `outlaw`,
		['shop'] = 'pdm',
	},
    ['akuma'] = {
		['name'] = 'Akuma',
		['brand'] = 'Dinka',
		['model'] = 'akuma',
		['price'] = 35000,
		['category'] = 'motorcycles',
		['hash'] = `akuma`,
		['shop'] = 'pdm',
	},
	['avarus'] = {
		['name'] = 'Avarus',
		['brand'] = 'LCC',
		['model'] = 'avarus',
		['price'] = 15000,
		['category'] = 'motorcycles',
		['hash'] = `avarus`,
		['shop'] = 'pdm',
	},
	['bagger'] = {
		['name'] = 'Bagger',
		['brand'] = 'WMC',
		['model'] = 'bagger',
		['price'] = 12500,
		['category'] = 'motorcycles',
		['hash'] = `bagger`,
		['shop'] = 'pdm',
	},
	['bati'] = {
		['name'] = 'Bati 801',
		['brand'] = 'Pegassi',
		['model'] = 'bati',
		['price'] = 25000,
		['category'] = 'motorcycles',
		['hash'] = `bati`,
		['shop'] = 'pdm',
	},
	['bf400'] = {
		['name'] = 'BF400',
		['brand'] = 'Nagasaki',
		['model'] = 'bf400',
		['price'] = 20000,
		['category'] = 'motorcycles',
		['hash'] = `bf400`,
		['shop'] = 'pdm',
	},
	['carbonrs'] = {
		['name'] = 'Carbon RS',
		['brand'] = 'Nagasaki',
		['model'] = 'carbonrs',
		['price'] = 22000,
		['category'] = 'motorcycles',
		['hash'] = `carbonrs`,
		['shop'] = 'pdm',
	},
	['chimera'] = {
		['name'] = 'Chimera',
		['brand'] = 'Nagasaki',
		['model'] = 'chimera',
		['price'] = 40000,
		['category'] = 'motorcycles',
		['hash'] = `chimera`,
		['shop'] = 'pdm',
	},
	['cliffhanger'] = {
		['name'] = 'Cliffhanger',
		['brand'] = 'Western',
		['model'] = 'cliffhanger',
		['price'] = 30000,
		['category'] = 'motorcycles',
		['hash'] = `cliffhanger`,
		['shop'] = 'pdm',
	},
	['daemon2'] = {
		['name'] = 'Daemon Custom',
		['brand'] = 'Western',
		['model'] = 'daemon2',
		['price'] = 23000,
		['category'] = 'motorcycles',
		['hash'] = `daemon2`,
		['shop'] = 'pdm',
	},
	['defiler'] = {
		['name'] = 'Defiler',
		['brand'] = 'Shitzu',
		['model'] = 'defiler',
		['price'] = 25000,
		['category'] = 'motorcycles',
		['hash'] = `defiler`,
		['shop'] = 'pdm',
	},
	['diablous2'] = {
		['name'] = 'Diablous Custom',
		['brand'] = 'Principe',
		['model'] = 'diablous2',
		['price'] = 35000,
		['category'] = 'motorcycles',
		['hash'] = `diablous2`,
		['shop'] = 'pdm',
	},
	['double'] = {
		['name'] = 'Double-T',
		['brand'] = 'Dinka',
		['model'] = 'double',
		['price'] = 50000,
		['category'] = 'motorcycles',
		['hash'] = `double`,
		['shop'] = 'pdm',
	},
	['enduro'] = {
		['name'] = 'Enduro',
		['brand'] = 'Dinka',
		['model'] = 'enduro',
		['price'] = 40000,
		['category'] = 'motorcycles',
		['hash'] = `enduro`,
		['shop'] = 'pdm',
	},
	['esskey'] = {
		['name'] = 'Esskey',
		['brand'] = 'Pegassi',
		['model'] = 'esskey',
		['price'] = 15000,
		['category'] = 'motorcycles',
		['hash'] = `esskey`,
		['shop'] = 'pdm',
	},
	['faggio'] = {
		['name'] = 'Faggio Sport',
		['brand'] = 'Pegassi',
		['model'] = 'faggio',
		['price'] = 5000,
		['category'] = 'motorcycles',
		['hash'] = `faggio`,
		['shop'] = 'pdm',
	},
	['faggio3'] = {
		['name'] = 'Chetak',
		['brand'] = 'Pegassi',
		['model'] = 'faggio3',
		['price'] = 2500,
		['category'] = 'motorcycles',
		['hash'] = `faggio3`,
		['shop'] = 'pdm',
	},
	['fcr2'] = {
		['name'] = 'FCR 1000 Custom',
		['brand'] = 'Pegassi',
		['model'] = 'fcr2',
		['price'] = 12000,
		['category'] = 'motorcycles',
		['hash'] = `fcr2`,
		['shop'] = 'pdm',
	},
	['gargoyle'] = {
		['name'] = 'Gargoyle',
		['brand'] = 'Western',
		['model'] = 'gargoyle',
		['price'] = 40000,
		['category'] = 'motorcycles',
		['hash'] = `gargoyle`,
		['shop'] = 'pdm',
	},
	['hakuchou'] = {
		['name'] = 'Hakuchou',
		['brand'] = 'Shitzu',
		['model'] = 'hakuchou',
		['price'] = 50000,
		['category'] = 'motorcycles',
		['hash'] = `hakuchou`,
		['shop'] = 'pdm',
	},
	['hakuchou2'] = {
		['name'] = 'Hakuchou Drag',
		['brand'] = 'Shitzu',
		['model'] = 'hakuchou2',
		['price'] = 145000,
		['category'] = 'motorcycles',
		['hash'] = `hakuchou2`,
		['shop'] = 'pdm',
	},
	['hexer'] = {
		['name'] = 'Hexer',
		['brand'] = 'LCC',
		['model'] = 'hexer',
		['price'] = 16000,
		['category'] = 'motorcycles',
		['hash'] = `hexer`,
		['shop'] = 'pdm',
	},
	['innovation'] = {
		['name'] = 'Innovation',
		['brand'] = 'LLC',
		['model'] = 'innovation',
		['price'] = 40000,
		['category'] = 'motorcycles',
		['hash'] = `innovation`,
		['shop'] = 'pdm',
	},
	['lectro'] = {
		['name'] = 'Lectro',
		['brand'] = 'Principe',
		['model'] = 'lectro',
		['price'] = 20000,
		['category'] = 'motorcycles',
		['hash'] = `lectro`,
		['shop'] = 'pdm',
	},
	['manchez2'] = {
		['name'] = 'Manchez',
		['brand'] = 'Maibatsu',
		['model'] = 'manchez2',
		['price'] = 45000,
		['category'] = 'motorcycles',
		['hash'] = `manchez2`,
		['shop'] = 'pdm',
	},
	['nightblade'] = {
		['name'] = 'Nightblade',
		['brand'] = 'WMC',
		['model'] = 'nightblade',
		['price'] = 50000,
		['category'] = 'motorcycles',
		['hash'] = `nightblade`,
		['shop'] = 'pdm',
	},
	['pcj'] = {
		['name'] = 'PCJ-600',
		['brand'] = 'Shitzu',
		['model'] = 'pcj',
		['price'] = 15000,
		['category'] = 'motorcycles',
		['hash'] = `pcj`,
		['shop'] = 'pdm',
	},
	['ruffian'] = {
		['name'] = 'Ruffian',
		['brand'] = 'Pegassi',
		['model'] = 'ruffian',
		['price'] = 15000,
		['category'] = 'motorcycles',
		['hash'] = `ruffian`,
		['shop'] = 'pdm',
	},
	['sanchez2'] = {
		['name'] = 'Sanchez',
		['brand'] = 'Maibatsu',
		['model'] = 'sanchez2',
		['price'] = 35000,
		['category'] = 'motorcycles',
		['hash'] = `sanchez2`,
		['shop'] = 'pdm',
	},
	['sanctus'] = {
		['name'] = 'Sanctus',
		['brand'] = 'LCC',
		['model'] = 'sanctus',
		['price'] = 80000,
		['category'] = 'motorcycles',
		['hash'] = `sanctus`,
		['shop'] = 'pdm',
	},
	['shotaro'] = {
		['name'] = 'Shotaro Concept',
		['brand'] = 'Nagasaki',
		['model'] = 'shotaro',
		['price'] = 320000,
		['category'] = 'motorcycles',
		['hash'] = `shotaro`,
		['shop'] = 'pdm',
	},
	['stryder'] = {
		['name'] = 'Stryder',
		['brand'] = 'Nagasaki',
		['model'] = 'stryder',
		['price'] = 50000,
		['category'] = 'motorcycles',
		['hash'] = `stryder`,
		['shop'] = 'pdm',
	},
    ['vindicator'] = {
		['name'] = 'Vindicator',
		['brand'] = 'Dinka',
		['model'] = 'vindicator',
		['price'] = 20000,
		['category'] = 'motorcycles',
		['hash'] = `vindicator`,
		['shop'] = 'pdm',
	},
	['vortex'] = {
		['name'] = 'Vortex',
		['brand'] = 'Pegassi',
		['model'] = 'vortex',
		['price'] = 31000,
		['category'] = 'motorcycles',
		['hash'] = `vortex`,
		['shop'] = 'pdm',
	},
	['wolfsbane'] = {
		['name'] = 'Wolfsbane',
		['brand'] = 'Western',
		['model'] = 'wolfsbane',
		['price'] = 60000,
		['category'] = 'motorcycles',
		['hash'] = `wolfsbane`,
		['shop'] = 'pdm',
	},
	['zombieb'] = {
		['name'] = 'Zombie Chopper',
		['brand'] = 'Western',
		['model'] = 'zombieb',
		['price'] = 25000,
		['category'] = 'motorcycles',
		['hash'] = `zombieb`,
		['shop'] = 'pdm',
	},
	['shinobi'] = {		--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Shinobi',
		['brand'] = 'Nagasaki',
		['model'] = 'shinobi',
		['price'] = 90000,
		['category'] = 'motorcycles',
		['hash'] = `shinobi`,
		['shop'] = 'pdm',
	},
	['reever'] = {		--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Reever',
		['brand'] = 'Western',
		['model'] = 'reever',
		['price'] = 80000,
		['category'] = 'motorcycles',
		['hash'] = `reever`,
		['shop'] = 'pdm',
	},

	--// Compacts
	
	['blista'] = {
		['name'] = 'Blista',
		['brand'] = 'Dinka',
		['model'] = 'blista',
		['price'] = 15000,
		['category'] = 'compacts',
		['hash'] = `blista`,
		['shop'] = 'pdm',
	},
	['brioso'] = {
		['name'] = 'Brioso R/A',
		['brand'] = 'Grotti',
		['model'] = 'brioso',
		['price'] = 20000,
		['category'] = 'compacts',
		['hash'] = `brioso`,
		['shop'] = 'pdm',
	},
	['kanjo'] = {
		['name'] = 'Blista Kanjo',
		['brand'] = 'Dinka',
		['model'] = 'kanjo',
		['price'] = 25000,
		['category'] = 'compacts',
		['hash'] = `kanjo`,
		['shop'] = 'pdm',
	},
	['issi2'] = {
		['name'] = 'Issi',
		['brand'] = 'Weeny',
		['model'] = 'issi2',
		['price'] = 20000,
		['category'] = 'compacts',
		['hash'] = `issi2`,
		['shop'] = 'pdm',
	},
	['issi3'] = {
		['name'] = 'Issi Classic',
		['brand'] = 'Weeny',
		['model'] = 'issi3',
		['price'] = 25000,
		['category'] = 'compacts',
		['hash'] = `issi3`,
		['shop'] = 'pdm',
	},
	['panto'] = {
		['name'] = 'Panto',
		['brand'] = 'Benefactor',
		['model'] = 'panto',
		['price'] = 23200,
		['category'] = 'compacts',
		['hash'] = `panto`,
		['shop'] = 'pdm',
	},
	['brioso2'] = {
		['name'] = 'Brioso 300',
		['brand'] = 'Grotti',
		['model'] = 'brioso2',
		['price'] = 25000,
		['category'] = 'compacts',
		['hash'] = `brioso2`,
		['shop'] = 'pdm',
	},
	['weevil'] = {
		['name'] = 'Weevil',
		['brand'] = 'BF',
		['model'] = 'weevil',
		['price'] = 30000,
		['category'] = 'compacts',
		['hash'] = `weevil`,
		['shop'] = 'pdm',
	},
	
	--// Coupes

	['minivan2'] = {
		['name'] = 'Minivan Custom',
		['brand'] = 'Vapid',
		['model'] = 'minivan2',
		['price'] = 60000,
		['category'] = 'coupes',
		['hash'] = `minivan2`,
		['shop'] = 'pdm',
	},
	['cogcabrio'] = {
		['name'] = 'Cognoscenti Cabrio',
		['brand'] = 'Enus',
		['model'] = 'cogcabrio',
		['price'] = 30000,
		['category'] = 'coupes',
		['hash'] = `cogcabrio`,
		['shop'] = 'pdm',
	},
	['exemplar'] = {
		['name'] = 'Exemplar',
		['brand'] = 'Dewbauchee',
		['model'] = 'exemplar',
		['price'] = 30000,
		['category'] = 'coupes',
		['hash'] = `exemplar`,
		['shop'] = 'pdm',
	},
	['f620'] = {
		['name'] = 'F620',
		['brand'] = 'Ocelot',
		['model'] = 'f620',
		['price'] = 38500,
		['category'] = 'coupes',
		['hash'] = `f620`,
		['shop'] = 'pdm',
	},
	['felon2'] = {
		['name'] = 'Felon GT',
		['brand'] = 'Lampadati',
		['model'] = 'felon2',
		['price'] = 40000,
		['category'] = 'coupes',
		['hash'] = `felon2`,
		['shop'] = 'pdm',
	},
	['jackal'] = {
		['name'] = 'Jackal',
		['brand'] = 'Ocelot',
		['model'] = 'jackal',
		['price'] = 30000,
		['category'] = 'coupes',
		['hash'] = `jackal`,
		['shop'] = 'pdm',
	},
	['windsor'] = {
		['name'] = 'Windsor',
		['brand'] = 'Enus',
		['model'] = 'windsor',
		['price'] = 250000,
		['category'] = 'coupes',
		['hash'] = `windsor`,
		['shop'] = 'pdm',
	},
	['windsor2'] = {
		['name'] = 'Windsor Drop',
		['brand'] = 'Enus',
		['model'] = 'windsor2',
		['price'] = 300000,
		['category'] = 'coupes',
		['hash'] = `windsor2`,
		['shop'] = 'pdm',
	},
	['previon'] = {			--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Previon',
		['brand'] = 'Karin',
		['model'] = 'previon',
		['price'] = 60000,
		['category'] = 'coupes',
		['hash'] = `previon`,
		['shop'] = 'pdm',
	},
	['sentinel3'] = {
		['name'] = 'Sentinel Classic',
		['brand'] = 'Übermacht',
		['model'] = 'sentinel3',
		['price'] = 60000,
		['category'] = 'coupes',
		['hash'] = `sentinel3`,
		['shop'] = 'pdm',
	},
	['futo2'] = {
		['name'] = 'Futo GTX',
		['brand'] = 'Karin',
		['model'] = 'futo2',
		['price'] = 40500,
		['category'] = 'coupes',
		['hash'] = `futo2`,
		['shop'] = 'pdm',
	},
	
	--// Cycles
	
	['bmx'] = {
		['name'] = 'BMX',
        ['brand'] = 'Bike',
		['model'] = 'bmx',
		['price'] = 200,
		['category'] = 'cycles',
		['hash'] = `bmx`,
		['shop'] = 'pdm',
	},
	['cruiser'] = {
		['name'] = 'Cruiser',
        ['brand'] = 'Bike',
		['model'] = 'cruiser',
		['price'] = 410,
		['category'] = 'cycles',
		['hash'] = `cruiser`,
		['shop'] = 'pdm',
	},
	['fixter'] = {
		['name'] = 'Fixter',
        ['brand'] = 'Bike',
		['model'] = 'fixter',
		['price'] = 525,
		['category'] = 'cycles',
		['hash'] = `fixter`,
		['shop'] = 'pdm',
	},
	['scorcher'] = {
		['name'] = 'Scorcher',
        ['brand'] = 'Bike',
		['model'] = 'scorcher',
		['price'] = 1080,
		['category'] = 'cycles',
		['hash'] = `scorcher`,
		['shop'] = 'pdm',
	},
	['tribike2'] = {
		['name'] = 'Tri Bike 2',
        ['brand'] = 'Bike',
		['model'] = 'tribike2',
		['price'] = 1500,
		['category'] = 'cycles',
		['hash'] = `tribike2`,
		['shop'] = 'pdm',
	},
	
	--// Muscle
	
	['blade'] = {
		['name'] = 'Blade',
		['brand'] = 'Vapid',
		['model'] = 'blade',
		['price'] = 25000,
		['category'] = 'muscle',
		['hash'] = `blade`,
		['shop'] = 'pdm',
	},
	['buccaneer'] = {
		['name'] = 'Buccaneer',
		['brand'] = 'Albany',
		['model'] = 'buccaneer',
		['price'] = 26000,
		['category'] = 'muscle',
		['hash'] = `buccaneer`,
		['shop'] = 'pdm',
	},
	['buccaneer2'] = {
		['name'] = 'Buccaneer Rider',
		['brand'] = 'Albany',
		['model'] = 'buccaneer2',
		['price'] = 30000,
		['category'] = 'muscle',
		['hash'] = `buccaneer2`,
		['shop'] = 'pdm',
	},
	['chino'] = {
		['name'] = 'Chino',
		['brand'] = 'Vapid',
		['model'] = 'chino',
		['price'] = 30000,
		['category'] = 'muscle',
		['hash'] = `chino`,
		['shop'] = 'pdm',
	},
	['chino2'] = {
		['name'] = 'Chino Luxe',
		['brand'] = 'Vapid',
		['model'] = 'chino2',
		['price'] = 45000,
		['category'] = 'muscle',
		['hash'] = `chino2`,
		['shop'] = 'pdm',
	},
	['coquette3'] = {
		['name'] = 'Coquette BlackFin',
		['brand'] = 'Invetero',
		['model'] = 'coquette3',
		['price'] = 60000,
		['category'] = 'muscle',
		['hash'] = `coquette3`,
		['shop'] = 'pdm',
	},
	['dominator'] = {
		['name'] = 'Dominator',
		['brand'] = 'Vapid',
		['model'] = 'dominator',
		['price'] = 40000,
		['category'] = 'muscle',
		['hash'] = `dominator`,
		['shop'] = 'pdm',
	},
	['dominator3'] = {
		['name'] = 'Dominator GTX',
		['brand'] = 'Vapid',
		['model'] = 'dominator3',
		['price'] = 90000,
		['category'] = 'muscle',
		['hash'] = `dominator3`,
		['shop'] = 'pdm',
	},
	['dominator7'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Dominator ASP',
		['brand'] = 'Vapid',
		['model'] = 'dominator7',
		['price'] = 70000,
		['category'] = 'muscle',
		['hash'] = `dominator7`,
		['shop'] = 'pdm',
	},
	['dukes'] = {
		['name'] = 'Dukes',
		['brand'] = 'Imponte',
		['model'] = 'dukes',
		['price'] = 20000,
		['category'] = 'muscle',
		['hash'] = `dukes`,
		['shop'] = 'pdm',
	},
	['ellie'] = {
		['name'] = 'Ellie',
		['brand'] = 'Vapid',
		['model'] = 'ellie',
		['price'] = 65000,
		['category'] = 'muscle',
		['hash'] = `ellie`,
		['shop'] = 'pdm',
	},
	['gauntlet'] = {
		['name'] = 'Gauntlet',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet',
		['price'] = 35000,
		['category'] = 'muscle',
		['hash'] = `gauntlet`,
		['shop'] = 'pdm',
	},
	['gauntlet3'] = {							--DLC
		['name'] = 'Classic Gauntlet',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet3',
		['price'] = 60000,
		['category'] = 'muscle',
		['hash'] = `gauntlet3`,
		['shop'] = 'pdm',
	},
	['gauntlet4'] = {							--DLC
		['name'] = 'Gauntlet Hellfire',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet4',
		['price'] = 100000,
		['category'] = 'muscle',
		['hash'] = `gauntlet4`,
		['shop'] = 'pdm',
	},
	['hotknife'] = {
		['name'] = 'Hotknife',
		['brand'] = 'Vapid',
		['model'] = 'hotknife',
		['price'] = 60000,
		['category'] = 'muscle',
		['hash'] = `hotknife`,
		['shop'] = 'pdm',
	},
	['hustler'] = {
		['name'] = 'Hustler',
		['brand'] = 'Vapid',
		['model'] = 'hustler',
		['price'] = 50000,
		['category'] = 'muscle',
		['hash'] = `hustler`,
		['shop'] = 'pdm',
	},
	['nightshade'] = {
		['name'] = 'Nightshade',
		['brand'] = 'Imponte',
		['model'] = 'nightshade',
		['price'] = 70000,
		['category'] = 'muscle',
		['hash'] = `nightshade`,
		['shop'] = 'pdm',
	},
	['peyote'] = {
		['name'] = 'Peyote',
		['brand'] = 'Vapid',
		['model'] = 'peyote',
		['price'] = 40000,
		['category'] = 'muscle',
		['hash'] = `peyote`,
		['shop'] = 'pdm',
	},
	['peyote3'] = {
		['name'] = 'Peyote Custom',
		['brand'] = 'Vapid',
		['model'] = 'peyote3',
		['price'] = 70000,
		['category'] = 'muscle',
		['hash'] = `peyote3`,
		['shop'] = 'pdm',
	},
	['peyote2'] = {							--DLC
		['name'] = 'Peyote Gasser',
		['brand'] = 'Vapid',
		['model'] = 'peyote2',
		['price'] = 60000,
		['category'] = 'muscle',
		['hash'] = `peyote2`,
		['shop'] = 'pdm',
	},
	['sabregt2'] = {
		['name'] = 'Sabre GT',
		['brand'] = 'Declasse',
		['model'] = 'sabregt2',
		['price'] = 40000,
		['category'] = 'muscle',
		['hash'] = `sabregt2`,
		['shop'] = 'pdm',
	},
	['slamvan3'] = {
		['name'] = 'Slam Van Custom',
		['brand'] = 'Vapid',
		['model'] = 'slamvan3',
		['price'] = 20000,
		['category'] = 'muscle',
		['hash'] = `slamvan3`,
		['shop'] = 'pdm',
	},
	['tampa'] = {
		['name'] = 'Tampa',
		['brand'] = 'Declasse',
		['model'] = 'tampa',
		['price'] = 35000,
		['category'] = 'muscle',
		['hash'] = `tampa`,
		['shop'] = 'pdm',
	},
	['tampa2'] = {
		['name'] = 'Drift Tampa',
		['brand'] = 'Declasse',
		['model'] = 'tampa2',
		['price'] = 100000,
		['category'] = 'muscle',
		['hash'] = `tampa2`,
		['shop'] = 'pdm',
	},
    ['voodoo'] = {
		['name'] = 'Voodoo',
		['brand'] = 'Declasse',
		['model'] = 'voodoo',
		['price'] = 30000,
		['category'] = 'muscle',
		['hash'] = `voodoo`,
		['shop'] = 'pdm',
	},
	['yosemite2'] = {
		['name'] = 'Yosemite Drift',
		['brand'] = 'Declasse',
		['model'] = 'yosemite2',
		['price'] = 65000,
		['category'] = 'muscle',
		['hash'] = `yosemite2`,
		['shop'] = 'pdm',
	},
	
	--// Off-Road
	
	['brawler'] = {
		['name'] = 'Brawler',
		['brand'] = 'Annis',
		['price'] = 55000,
		['category'] = 'offroad',
		['model'] = 'brawler',
		['hash'] = `brawler`,
		['shop'] = 'pdm',
	},
	['caracara2'] = {							--DLC
		['name'] = 'Caracara 4x4',
		['brand'] = 'Vapid',
		['model'] = 'caracara2',
		['price'] = 150000,
		['category'] = 'offroad',
		['hash'] = `caracara2`,
		['shop'] = 'pdm',
	},
	['dubsta3'] = {
		['name'] = 'Dubsta 6x6',
		['brand'] = 'Annis',
		['price'] = 200000,
		['category'] = 'offroad',
		['model'] = 'dubsta3',
		['hash'] = `dubsta3`,
		['shop'] = 'pdm',
	},
	['everon'] = {
		['name'] = 'Everon',
		['brand'] = 'Karin',
		['model'] = 'everon',
		['price'] = 160000,
		['category'] = 'offroad',
		['hash'] = `everon`,
		['shop'] = 'pdm',
	},
	['freecrawler'] = {							--DLC
		['name'] = 'Freecrawler',
		['brand'] = 'Canis',
		['model'] = 'freecrawler',
		['price'] = 125000,
		['category'] = 'offroad',
		['hash'] = `freecrawler`,
		['shop'] = 'pdm',
	},
	['hellion'] = {							--DLC
		['name'] = 'Hellion',
		['brand'] = 'Annis',
		['model'] = 'hellion',
		['price'] = 125000,
		['category'] = 'offroad',
		['hash'] = `hellion`,
		['shop'] = 'pdm',
	},
	['kamacho'] = {
		['name'] = 'Kamacho',
		['brand'] = 'Canis',
		['model'] = 'kamacho',
		['price'] = 200000,
		['category'] = 'offroad',
		['hash'] = `kamacho`,
		['shop'] = 'pdm',
	},
	['mesa3'] = {
		['name'] = 'Mesa Merryweather',
		['brand'] = 'Canis',
		['model'] = 'mesa3',
		['price'] = 50000,
		['category'] = 'offroad',
		['hash'] = `mesa3`,
		['shop'] = 'pdm',
	},
	['riata'] = {
		['name'] = 'Riata',
		['brand'] = 'Vapid',
		['model'] = 'riata',
		['price'] = 70000,
		['category'] = 'offroad',
		['hash'] = `riata`,
		['shop'] = 'pdm',
	},
	['trophytruck'] = {
		['name'] = 'Trophy Truck',
		['brand'] = 'Annis',
		['price'] = 70000,
		['category'] = 'offroad',
		['model'] = 'trophytruck',
		['hash'] = `trophytruck`,
		['shop'] = 'pdm',
	},
	['trophytruck2'] = {
		['name'] = 'Trophy Truck Limited',
		['brand'] = 'Annis',
		['price'] = 90000,
		['category'] = 'offroad',
		['model'] = 'trophytruck2',
		['hash'] = `trophytruck2`,
		['shop'] = 'pdm',
	},
	['vagrant'] = {
		['name'] = 'Vagrant',
		['brand'] = 'Maxwell',
		['price'] = 50000,
		['category'] = 'offroad',
		['model'] = 'vagrant',
		['hash'] = `vagrant`,
		['shop'] = 'pdm',
	},
	['winky'] = {
		['name'] = 'Winky',
		['brand'] = 'Vapid',
		['price'] = 87000,
		['category'] = 'offroad',
		['model'] = 'winky',
		['hash'] = `winky`,
		['shop'] = 'pdm',
	},
	
	--// SUVs
	
	['baller3'] = {
		['name'] = 'Baller LE',
		['brand'] = 'Gallivanter',
		['model'] = 'baller3',
		['price'] = 150000,
		['category'] = 'suvs',
		['hash'] = `baller3`,
		['shop'] = 'pdm',
	},
	['baller7'] = { 	 	--
		['name'] = 'Baller ST',
		['brand'] = 'Gallivanter',
		['model'] = 'baller7',
		['price'] = 185000,
		['category'] = 'suvs',
		['hash'] = `baller7`,
		['shop'] = 'pdm',
	},
	['cavalcade2'] = {
		['name'] = 'Cavalcade',
		['brand'] = 'Albany',
		['model'] = 'cavalcade2',
		['price'] = 45000,
		['category'] = 'suvs',
		['hash'] = `cavalcade2`,
		['shop'] = 'pdm',
	},
	['dubsta2'] = {
		['name'] = 'Dubsta Luxuary',
		['brand'] = 'Benefactor',
		['model'] = 'dubsta2',
		['price'] = 170000,
		['category'] = 'suvs',
		['hash'] = `dubsta2`,
		['shop'] = 'pdm',
	},
	['granger'] = {
		['name'] = 'Granger',
		['brand'] = 'Declasse',
		['model'] = 'granger',
		['price'] = 55000,
		['category'] = 'suvs',
		['hash'] = `granger`,
		['shop'] = 'pdm',
	},
	['huntley'] = {
		['name'] = 'Huntley S',
		['brand'] = 'Enus',
		['model'] = 'huntley',
		['price'] = 45000,
		['category'] = 'suvs',
		['hash'] = `huntley`,
		['shop'] = 'pdm',
	},
	['novak'] = {							--DLC
		['name'] = 'Novak',
		['brand'] = 'Lampadati',
		['model'] = 'novak',
		['price'] = 80000,
		['category'] = 'suvs',
		['hash'] = `novak`,
		['shop'] = 'pdm',
	},
	['patriot2'] = {
		['name'] = 'Patriot',
		['brand'] = 'Mammoth',
		['model'] = 'patriot2',
		['price'] = 150000,
		['category'] = 'suvs',
		['hash'] = `patriot2`,
		['shop'] = 'pdm',
	},
	['rebla'] = {
		['name'] = 'Rebla GTS',
		['brand'] = 'Übermacht',
		['model'] = 'rebla',
		['price'] = 100000,
		['category'] = 'suvs',
		['hash'] = `rebla`,
		['shop'] = 'pdm',
	},
	['toros'] = {							--DLC
		['name'] = 'Toros',
		['brand'] = 'Pegassi',
		['model'] = 'toros',
		['price'] = 350000,
		['category'] = 'suvs',
		['hash'] = `toros`,
		['shop'] = 'pdm',
	},
	['xls'] = {
		['name'] = 'XLS',
		['brand'] = 'Benefactor',
		['model'] = 'xls',
		['price'] = 75000,
		['category'] = 'suvs',
		['hash'] = `xls`,
		['shop'] = 'pdm',
	},
        ['iwagen'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Obey',
		['brand'] = 'I-Wagen',
		['model'] = 'iwagen',
		['price'] = 145000,
		['category'] = 'suvs',
		['hash'] = `iwagen`,
		['shop'] = 'pdm',
	},
	['astron'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Pfister',
		['brand'] = 'Astron',
		['model'] = 'astron',
		['price'] = 150000,
		['category'] = 'suvs',
		['hash'] = `astron`,
		['shop'] = 'pdm',
	},
	
	--// Sedans
	
	['cognoscenti'] = {
		['name'] = 'Cognoscenti',
		['brand'] = 'Enus',
		['model'] = 'cognoscenti',
		['price'] = 25000,
		['category'] = 'sedans',
		['hash'] = `cognoscenti`,
		['shop'] = 'pdm',
	},
	['stretch'] = {
		['name'] = 'Stretch',
		['brand'] = 'Dundreary',
		['model'] = 'stretch',
		['price'] = 130000,
		['category'] = 'sedans',
		['hash'] = `stretch`,
		['shop'] = 'pdm',
	},
	['superd'] = {
		['name'] = 'Super Diamond',
		['brand'] = 'Enus',
		['model'] = 'superd',
		['price'] = 90000,
		['category'] = 'sedans',
		['hash'] = `superd`,
		['shop'] = 'pdm',
	},
	['surge'] = {
		['name'] = 'Surge',
		['brand'] = 'Cheval',
		['model'] = 'surge',
		['price'] = 30000,
		['category'] = 'sedans',
		['hash'] = `surge`,
		['shop'] = 'pdm',
	},
	['tailgater2'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Tailgater S',
		['brand'] = 'Obey',
		['model'] = 'tailgater2',
		['price'] = 70000,
		['category'] = 'sedans',
		['hash'] = `tailgater2`,
		['shop'] = 'pdm',
	},
	['cinquemila'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Lampadati',
		['brand'] = 'Cinquemila',
		['model'] = 'cinquemila',
		['price'] = 85000,
		['category'] = 'sedans',
		['hash'] = `cinquemila`,
		['shop'] = 'pdm',
	},
	
	--// Sports 
	
	['Khamelion'] = {
		['name'] = 'Khamelion',
		['brand'] = 'Hijak',
		['model'] = 'Khamelion',
		['price'] = 125000,
		['category'] = 'sports',
		['hash'] = `Khamelion`,
		['shop'] = 'pdm',
	},
	['raiden'] = {
		['name'] = 'Raiden',
		['brand'] = 'Coil',
		['model'] = 'raiden',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `raiden`,
		['shop'] = 'pdm',
	},
	['schafter3'] = {
		['name'] = 'Schafter v12',
		['brand'] = 'Benefactor',
		['model'] = 'schafter3',
		['price'] = 200000,
		['category'] = 'sports',
		['hash'] = `schafter3`,
		['shop'] = 'pdm',
	},
	['euros'] = {
		['name'] = 'Euros',
		['brand'] = 'Annis',
		['model'] = 'euros',
		['price'] = 180000,
		['category'] = 'sports',
		['hash'] = `euros`,
		['shop'] = 'pdm',
	},
	['remus'] = {
		['name'] = 'Remus',
		['brand'] = 'Annis',
		['model'] = 'remus',
		['price'] = 120000,
		['category'] = 'sports',
		['hash'] = `remus`,
		['shop'] = 'pdm',
	},
    ['bestiagts'] = {
		['name'] = 'Bestia GTS',
		['brand'] = 'Grotti',
		['model'] = 'bestiagts',
		['price'] = 140000,
		['category'] = 'sports',
		['hash'] = `bestiagts`,
		['shop'] = 'pdm',
	},
	['buffalo2'] = {
		['name'] = 'Buffalo S',
		['brand'] = 'Bravado',
		['model'] = 'buffalo2',
		['price'] = 65000,
		['category'] = 'sports',
		['hash'] = `buffalo2`,
		['shop'] = 'pdm',
	},
	['comet3'] = {
		['name'] = 'Comet Retro Custom',
		['brand'] = 'Pfister',
		['model'] = 'comet3',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `comet3`,
		['shop'] = 'pdm',
	},
	['comet5'] = {
		['name'] = 'Comet SR',
		['brand'] = 'Pfister',
		['model'] = 'comet5',
		['price'] = 165000,
		['category'] = 'sports',
		['hash'] = `comet5`,
		['shop'] = 'pdm',
	},
	['comet6'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Comet S2',
		['brand'] = 'Pfister',
		['model'] = 'comet6',
		['price'] = 180000,
		['category'] = 'sports',
		['hash'] = `comet6`,
		['shop'] = 'pdm',
	},
	['comet7'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Comet',
		['brand'] = 'S2 Cabrio',
		['model'] = 'comet7',
		['price'] = 200000,
		['category'] = 'sedans',
		['hash'] = `comet7`,
		['shop'] = 'pdm',
	},
	['coquette4'] = {
		['name'] = 'Coquette D10',
		['brand'] = 'Invetero',
		['model'] = 'coquette4',
		['price'] = 400000,
		['category'] = 'sports',
		['hash'] = `coquette4`,
		['shop'] = 'pdm',
	},
	['drafter'] = {							--DLC
		['name'] = '8F Drafter',
		['brand'] = 'Obey',
		['model'] = 'drafter',
		['price'] = 120000,
		['category'] = 'sports',
		['hash'] = `drafter`,
		['shop'] = 'pdm',
	},
	['elegy'] = {							--DLC
		['name'] = 'Elegy Retro Custom',
		['brand'] = 'Annis',
		['model'] = 'elegy',
		['price'] = 125000,
		['category'] = 'sports',
		['hash'] = `elegy`,
		['shop'] = 'pdm',
	},
	['elegy2'] = {
		['name'] = 'Elegy RH8',
		['brand'] = 'Annis',
		['model'] = 'elegy2',
		['price'] = 100000,
		['category'] = 'sports',
		['hash'] = `elegy2`,
		['shop'] = 'pdm',
	},
	['flashgt'] = {
		['name'] = 'Flash GT',
		['brand'] = 'Vapid',
		['model'] = 'flashgt',
		['price'] = 140000,
		['category'] = 'sports',
		['hash'] = `flashgt`,
		['shop'] = 'pdm',
	},
	['furoregt'] = {
		['name'] = 'Furore GT',
		['brand'] = 'Lampadati',
		['model'] = 'furoregt',
		['price'] = 70000,
		['category'] = 'sports',
		['hash'] = `furoregt`,
		['shop'] = 'pdm',
	},
	['gb200'] = {
		['name'] = 'GB 200',
		['brand'] = 'Vapid',
		['model'] = 'gb200',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `gb200`,
		['shop'] = 'pdm',
	},
	['komoda'] = {
		['name'] = 'Komoda',
		['brand'] = 'Lampadati',
		['model'] = 'komoda',
		['price'] = 95000,
		['category'] = 'sports',
		['hash'] = `komoda`,
		['shop'] = 'pdm',
	},
	['jugular'] = {							--DLC
		['name'] = 'Jugular',
		['brand'] = 'Ocelot',
		['model'] = 'jugular',
		['price'] = 180000,
		['category'] = 'sports',
		['hash'] = `jugular`,
		['shop'] = 'pdm',
	},
	['jester'] = {
		['name'] = 'Jester',
		['brand'] = 'Dinka',
		['model'] = 'jester',
		['price'] = 85000,
		['category'] = 'sports',
		['hash'] = `jester`,
		['shop'] = 'pdm',
	},
	['jester2'] = {
		['name'] = 'Jester Racecar',
		['brand'] = 'Dinka',
		['model'] = 'jester2',
		['price'] = 175000,
		['category'] = 'sports',
		['hash'] = `jester2`,
		['shop'] = 'pdm',
	},
	['jester3'] = {
		['name'] = 'Jester Classic',
		['brand'] = 'Dinka',
		['model'] = 'jester3',
		['price'] = 125000,
		['category'] = 'sports',
		['hash'] = `jester3`,
		['shop'] = 'pdm',
	},
	['jester4'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Jester RR',
		['brand'] = 'Dinka',
		['model'] = 'jester4',
		['price'] = 200000,
		['category'] = 'sports',
		['hash'] = `jester4`,
		['shop'] = 'pdm',
	},
	['kuruma'] = {
		['name'] = 'Kuruma',
		['brand'] = 'Karin',
		['model'] = 'kuruma',
		['price'] = 75000,
		['category'] = 'sports',
		['hash'] = `kuruma`,
		['shop'] = 'pdm',
	},
	['locust'] = {							--DLC
		['name'] = 'Locust',
		['brand'] = 'Ocelot',
		['model'] = 'locust',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `locust`,
		['shop'] = 'pdm',
	},
	['lynx'] = {
		['name'] = 'Lynx',
		['brand'] = 'Ocelot',
		['model'] = 'lynx',
		['price'] = 125000,
		['category'] = 'sports',
		['hash'] = `lynx`,
		['shop'] = 'pdm',
	},
	['massacro2'] = {
		['name'] = 'Massacro Racecar',
		['brand'] = 'Dewbauchee',
		['model'] = 'massacro2',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `massacro2`,
		['shop'] = 'pdm',
	},
	['neon'] = {							--DLC
		['name'] = 'Neon',
		['brand'] = 'Pfister',
		['model'] = 'neon',
		['price'] = 300000,
		['category'] = 'sports',
		['hash'] = `neon`,
		['shop'] = 'pdm',
	},
	['paragon'] = {							--DLC
		['name'] = 'Paragon',
		['brand'] = 'Enus',
		['model'] = 'paragon',
		['price'] = 200000,
		['category'] = 'sports',
		['hash'] = `paragon`,
		['shop'] = 'pdm',
	},
	['pariah'] = {
		['name'] = 'Pariah',
		['brand'] = 'Ocelot',
		['model'] = 'pariah',
		['price'] = 90000,
		['category'] = 'sports',
		['hash'] = `pariah`,
		['shop'] = 'pdm',
	},
	['penumbra2'] = {
		['name'] = 'Penumbra FF',
		['brand'] = 'Maibatsu',
		['model'] = 'penumbra2',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `penumbra2`,
		['shop'] = 'pdm',
	},
	['rapidgt2'] = {
		['name'] = 'Rapid GT Convertible',
		['brand'] = 'Dewbauchee',
		['model'] = 'rapidgt2',
		['price'] = 90000,
		['category'] = 'sports',
		['hash'] = `rapidgt2`,
		['shop'] = 'pdm',
	},
    ['revolter'] = {
		['name'] = 'Revolter',
		['brand'] = 'Ubermacht',
		['model'] = 'revolter',
		['price'] = 65000,
		['category'] = 'sports',
		['hash'] = `revolter`,
		['shop'] = 'pdm',
	},
	['ruston'] = {
		['name'] = 'Ruston',
		['brand'] = 'Hijak',
		['model'] = 'ruston',
		['price'] = 100000,
		['category'] = 'sports',
		['hash'] = `ruston`,
		['shop'] = 'pdm',
	},
	['schlagen'] = {							--DLC
		['name'] = 'Schlagen GT',
		['brand'] = 'Benefactor',
		['model'] = 'schlagen',
		['price'] = 250000,
		['category'] = 'sports',
		['hash'] = `schlagen`,
		['shop'] = 'pdm',
	},
	['seven70'] = {
		['name'] = 'Seven-70',
		['brand'] = 'Dewbauchee',
		['model'] = 'seven70',
		['price'] = 100000,
		['category'] = 'sports',
		['hash'] = `seven70`,
		['shop'] = 'pdm',
	},
	['specter2'] = {
		['name'] = 'Specter Custom',
		['brand'] = 'Dewbauchee',
		['model'] = 'specter2',
		['price'] = 140000,
		['category'] = 'sports',
		['hash'] = `specter2`,
		['shop'] = 'pdm',
	},
	['fk8'] = {
		['name'] = 'Honda Civic',
		['brand'] = 'Honda',
		['model'] = 'fk8',
		['price'] = 250000,
		['category'] = 'sports',
		['hash'] = `fk8`,
		['shop'] = 'pdm',
	},
	['sultan'] = {
		['name'] = 'Sultan',
		['brand'] = 'Karin',
		['model'] = 'sultan',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `sultan`,
		['shop'] = 'pdm',
	},
	['sultan2'] = {
		['name'] = 'Sultan Custom',
		['brand'] = 'Karin',
		['model'] = 'sultan2',
		['price'] = 120000,
		['category'] = 'sports',
		['hash'] = `sultan2`,
		['shop'] = 'pdm',
	},
	['sultan3'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Sultan Classic Custom',
		['brand'] = 'Karin',
		['model'] = 'sultan3',
		['price'] = 100000,
		['category'] = 'sports',
		['hash'] = `sultan3`,
		['shop'] = 'pdm',
	},
	['sultanrs'] = {
		['name'] = 'Sultan RS',
		['brand'] = 'Karin',
		['model'] = 'sultanrs',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `sultanrs`,
		['shop'] = 'pdm',
	},
	['surano'] = {
		['name'] = 'Surano',
		['brand'] = ' Benefactor',
		['model'] = 'surano',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `surano`,
		['shop'] = 'pdm',
	},
	['verlierer2'] = {
		['name'] = 'Verlierer',
		['brand'] = 'Bravado',
		['model'] = 'verlierer2',
		['price'] = 100000,
		['category'] = 'sports',
		['hash'] = `verlierer2`,
		['shop'] = 'pdm',
	},
	['vstr'] = {
		['name'] = 'V-STR',
		['brand'] = 'Albany',
		['model'] = 'vstr',
		['price'] = 70000,
		['category'] = 'sports',
		['hash'] = `vstr`,
		['shop'] = 'pdm',
	},
	['zr350'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'ZR350',
		['brand'] = 'Annis',
		['model'] = 'zr350',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `zr350`,
		['shop'] = 'pdm',
	},
	['calico'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Calico GTF',
		['brand'] = 'Karin',
		['model'] = 'calico',
		['price'] = 170000,
		['category'] = 'sports',
		['hash'] = `calico`,
		['shop'] = 'pdm',
	},
	['growler'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Growler',
		['brand'] = 'Pfister',
		['model'] = 'growler',
		['price'] = 180000,
		['category'] = 'sports',
		['hash'] = `growler`,
		['shop'] = 'pdm',
	},
	['vectre'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Emperor Vectre',
		['brand'] = 'Emperor',
		['model'] = 'vectre',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `vectre`,
		['shop'] = 'pdm',
	},
	['cypher'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Cypher',
		['brand'] = 'Ubermacht',
		['model'] = 'cypher',
		['price'] = 170000,
		['category'] = 'sports',
		['hash'] = `cypher`,
		['shop'] = 'pdm',
	},
	
	--// Sports Classic

	['stafford'] = {							--DLC
		['name'] = 'Stafford',
		['brand'] = 'Enus',
		['model'] = 'stafford',
		['price'] = 150000,
		['category'] = 'sportsclassics',
		['hash'] = `stafford`,
		['shop'] = 'pdm',
	},
	['btype'] = {              
		['name'] = 'Roosevelt',
		['brand'] = 'Albany',
		['model'] = 'btype',
		['price'] = 300000,
		['category'] = 'sportsclassics',
		['hash'] = `btype`,
		['shop'] = 'pdm',
	},
	['btype2'] = {
		['name'] = 'Franken Stange',
		['brand'] = 'Albany',
		['model'] = 'btype2',
		['price'] = 287000,
		['category'] = 'sportsclassics',
		['hash'] = `btype2`,
		['shop'] = 'pdm',
	},
	['casco'] = {
		['name'] = 'Casco',
		['brand'] = 'Lampadati',
		['model'] = 'casco',
		['price'] = 125000,
		['category'] = 'sportsclassics',
		['hash'] = `casco`,
		['shop'] = 'pdm',
	},
	['dynasty'] = {							--DLC
		['name'] = 'Dynasty',
		['brand'] = 'Weeny',
		['model'] = 'dynasty',
		['price'] = 25000,
		['category'] = 'sportsclassic',
		['hash'] = `dynasty`,
		['shop'] = 'pdm',
	},
	['feltzer3'] = {							--DLC
		['name'] = 'Stirling GT',
		['brand'] = 'Benefactor',
		['model'] = 'feltzer3',
		['price'] = 120000,
		['category'] = 'sportsclassics',
		['hash'] = `feltzer3`,
		['shop'] = 'pdm',
	},
	['gt500'] = {
		['name'] = 'GT500',
		['brand'] = 'Grotti',
		['model'] = 'gt500',
		['price'] = 130000,
		['category'] = 'sportsclassics',
		['hash'] = `gt500`,
		['shop'] = 'pdm',
	},
	['infernus2'] = {
		['name'] = 'Infernus Classic',
		['brand'] = 'Pegassi',
		['model'] = 'infernus2',
		['price'] = 100000,
		['category'] = 'sportsclassics',
		['hash'] = `infernus2`,
		['shop'] = 'pdm',
	},
	['mamba'] = {
		['name'] = 'Mamba',
		['brand'] = 'Declasse',
		['model'] = 'mamba',
		['price'] = 140000,
		['category'] = 'sportsclassics',
		['hash'] = `mamba`,
		['shop'] = 'pdm',
	},
	['michelli'] = {
		['name'] = 'Michelli GT',
		['brand'] = 'Lampadati',
		['model'] = 'michelli',
		['price'] = 75000,
		['category'] = 'sportsclassic',
		['hash'] = `michelli`,
		['shop'] = 'pdm',
	},
	['monroe'] = {
		['name'] = 'Monroe',
		['brand'] = 'Pegassi',
		['model'] = 'monroe',
		['price'] = 115000,
		['category'] = 'sportsclassics',
		['hash'] = `monroe`,
		['shop'] = 'pdm',
	},
	['rapidgt3'] = {
		['name'] = 'Rapid GT',
		['brand'] = 'Dewbauchee',
		['model'] = 'rapidgt3',
		['price'] = 80000,
		['category'] = 'sportsclassics',
		['hash'] = `rapidgt3`,
		['shop'] = 'pdm',
	},
	['savestra'] = {
		['name'] = 'Savestra',
		['brand'] = 'Annis',
		['model'] = 'savestra',
		['price'] = 60000,
		['category'] = 'sportsclassic',
		['hash'] = `savestra`,
		['shop'] = 'pdm',
	},
	['stingergt'] = {
		['name'] = 'Stinger GT',
		['brand'] = 'Grotti',
		['model'] = 'stingergt',
		['price'] = 150000,
		['category'] = 'sportsclassics',
		['hash'] = `stingergt`,
		['shop'] = 'pdm',
	},
	['tornado2'] = {
		['name'] = 'Tornado Gang',
		['brand'] = 'Declasse',
		['model'] = 'tornado2',
		['price'] = 100000,
		['category'] = 'sportsclassic',
		['hash'] = `tornado2`,
		['shop'] = 'pdm',
	},
	['z190'] = {
		['name'] = '190Z',
		['brand'] = 'Karin',
		['model'] = 'z190',
		['price'] = 100000,
		['category'] = 'sportsclassics',
		['hash'] = `z190`,
		['shop'] = 'pdm',
	},
	['ztype'] = {
		['name'] = 'Z-Type',
		['brand'] = 'Truffade',
		['model'] = 'ztype',
		['price'] = 270000,
		['category'] = 'sportsclassics',
		['hash'] = `ztype`,
		['shop'] = 'pdm',
	},
	['zion3'] = {							--DLC
		['name'] = 'Zion Classic',
		['brand'] = 'Übermacht',
		['model'] = 'zion3',
		['price'] = 45000,
		['category'] = 'sportsclassic',
		['hash'] = `zion3`,
		['shop'] = 'pdm',
	},
	
	--// Super

	['italirsx'] = {
		['name'] = 'Itali RSX',
		['brand'] = 'Progen',
		['model'] = 'italirsx',
		['price'] = 560000,
		['category'] = 'super',
		['hash'] = `italirsx`,
		['shop'] = 'pdm',
	},
	['visione'] = {
		['name'] = 'Visione',
		['brand'] = 'Grotti',
		['model'] = 'visione',
		['price'] = 650000,
		['category'] = 'super',
		['hash'] = `visione`,
		['shop'] = 'pdm',
	},
	['deveste'] = {							--DLC
		['name'] = 'Deveste',
		['brand'] = 'Principe',
		['model'] = 'deveste',
		['price'] = 540000,
		['category'] = 'super',
		['hash'] = `deveste`,
		['shop'] = 'pdm',
	},
	['cheetah2'] = {
		['name'] = 'Cheetah Classic',
		['brand'] = 'Grotti',
		['model'] = 'cheetah2',
		['price'] = 150000,
		['category'] = 'super',
		['hash'] = `cheetah2`,
		['shop'] = 'pdm',
	},
	['adder'] = {
		['name'] = 'Adder',
		['brand'] = 'Truffade',
		['model'] = 'adder',
		['price'] = 280000,
		['category'] = 'super',
		['hash'] = `adder`,
		['shop'] = 'pdm',
	},
	['autarch'] = {
		['name'] = 'Autarch',
		['brand'] = 'Överflöd',
		['model'] = 'autarch',
		['price'] = 250000,
		['category'] = 'super',
		['hash'] = `autarch`,
		['shop'] = 'pdm',
	},
	['banshee2'] = {
		['name'] = 'Banshee 900R',
		['brand'] = 'Bravado',
		['model'] = 'banshee2',
		['price'] = 140000,
		['category'] = 'super',
		['hash'] = `banshee2`,
		['shop'] = 'pdm',
	},
	['bullet'] = {
		['name'] = 'Bullet',
		['brand'] = 'Vapid',
		['model'] = 'bullet',
		['price'] = 140000,
		['category'] = 'super',
		['hash'] = `bullet`,
		['shop'] = 'pdm',
	},
    ['cyclone'] = {         --might be too overpowered
		['name'] = 'Cyclone',
		['brand'] = 'Coil',
		['model'] = 'cyclone',
		['price'] = 350000,
		['category'] = 'super',
		['hash'] = `cyclone`,
		['shop'] = 'pdm',
	},
	['entity2'] = {
		['name'] = 'Entity XXR',
		['brand'] = 'Överflöd',
		['model'] = 'entity2',
		['price'] = 450000,
		['category'] = 'super',
		['hash'] = `entity2`,
		['shop'] = 'pdm',
	},
	['emerus'] = {							--DLC
		['name'] = 'Emerus',
		['brand'] = 'Progen',
		['model'] = 'emerus',
		['price'] = 320000,
		['category'] = 'super',
		['hash'] = `emerus`,
		['shop'] = 'pdm',
	},
	['fmj'] = {
		['name'] = 'FMJ',
		['brand'] = 'Vapid',
		['model'] = 'fmj',
		['price'] = 430000,
		['category'] = 'super',
		['hash'] = `fmj`,
		['shop'] = 'pdm',
	},
	['furia'] = {
		['name'] = 'Furia',
		['brand'] = 'Grotti',
		['model'] = 'furia',
		['price'] = 400000,
		['category'] = 'super',
		['hash'] = `furia`,
		['shop'] = 'pdm',
	},
	['italigtb2'] = {
		['name'] = 'Itali GTB',
		['brand'] = 'Progen',
		['model'] = 'italigtb2',
		['price'] = 300000,
		['category'] = 'super',
		['hash'] = `italigtb2`,
		['shop'] = 'pdm',
	},
	['krieger'] = {							--DLC
		['name'] = 'Krieger',
		['brand'] = 'Benefactor',
		['model'] = 'krieger',
		['price'] = 520000,
		['category'] = 'super',
		['hash'] = `krieger`,
		['shop'] = 'pdm',
	},
	['nero'] = {
		['name'] = 'Nero',
		['brand'] = 'Truffade',
		['model'] = 'nero',
		['price'] = 400000,
		['category'] = 'super',
		['hash'] = `nero`,
		['shop'] = 'pdm',
	},
	['nero2'] = {
		['name'] = 'Nero Custom',
		['brand'] = 'Truffade',
		['model'] = 'nero2',
		['price'] = 450000,
		['category'] = 'super',
		['hash'] = `nero2`,
		['shop'] = 'pdm',
	},
	['osiris'] = {
		['name'] = 'Osiris',
		['brand'] = 'Pegassi',
		['model'] = 'osiris',
		['price'] = 200000,
		['category'] = 'super',
		['hash'] = `osiris`,
		['shop'] = 'pdm',
	},
	['penetrator'] = {
		['name'] = 'Penetrator',
		['brand'] = 'Ocelot',
		['model'] = 'penetrator',
		['price'] = 130000,
		['category'] = 'super',
		['hash'] = `penetrator`,
		['shop'] = 'pdm',
	},
	['pfister811'] = {
		['name'] = '811',
		['brand'] = 'Pfister',
		['model'] = 'pfister811',
		['price'] = 320000,
		['category'] = 'super',
		['hash'] = `pfister811`,
		['shop'] = 'pdm',
	},
	['prototipo'] = {
		['name'] = 'X80 Proto',
		['brand'] = 'Grotti',
		['model'] = 'prototipo',
		['price'] = 850000,
		['category'] = 'super',
		['hash'] = `prototipo`,
		['shop'] = 'pdm',
	},
	['reaper'] = {
		['name'] = 'Reaper',
		['brand'] = 'Pegassi',
		['model'] = 'reaper',
		['price'] = 250000,
		['category'] = 'super',
		['hash'] = `reaper`,
		['shop'] = 'pdm',
	},
	['sc1'] = {
		['name'] = 'SC1',
		['brand'] = 'Übermacht',
		['model'] = 'sc1',
		['price'] = 140000,
		['category'] = 'super',
		['hash'] = `sc1`,
		['shop'] = 'pdm',
	},
	['t20'] = {
		['name'] = 'T20',
		['brand'] = 'Progen',
		['model'] = 't20',
		['price'] = 560000,
		['category'] = 'super',
		['hash'] = `t20`,
		['shop'] = 'pdm',
	},
	['taipan'] = {
		['name'] = 'Taipan',
		['brand'] = 'Cheval',
		['model'] = 'taipan',
		['price'] = 300000,
		['category'] = 'super',
		['hash'] = `taipan`,
		['shop'] = 'pdm',
	},
	['tempesta'] = {
		['name'] = 'Tempesta',
		['brand'] = 'Pegassi',
		['model'] = 'tempesta',
		['price'] = 200000,
		['category'] = 'super',
		['hash'] = `tempesta`,
		['shop'] = 'pdm',
	},
	['tezeract'] = {
		['name'] = 'Tezeract',
		['brand'] = 'Pegassi',
		['model'] = 'tezeract',
		['price'] = 420000,
		['category'] = 'super',
		['hash'] = `tezeract`,
		['shop'] = 'pdm',
	},
    ['imorgon'] = {
		['name'] = 'Imorgon',
		['brand'] = 'Overflod',
		['model'] = 'imorgon',
		['price'] = 250000,
		['category'] = 'super',
		['hash'] = `imorgon`,
		['shop'] = 'pdm',
	},
    ['neo'] = {							--DLC
		['name'] = 'Neo',
		['brand'] = 'Vysser',
		['model'] = 'neo',
		['price'] = 200000,
		['category'] = 'super',
		['hash'] = `neo`,
		['shop'] = 'pdm',
	},
	['italigto'] = {							--DLC
		['name'] = 'Itali GTO',
		['brand'] = 'Progen',
		['model'] = 'italigto',
		['price'] = 400000,
		['category'] = 'super',
		['hash'] = `italigto`,
		['shop'] = 'pdm',
	},
	['thrax'] = {							--DLC
		['name'] = 'Thrax',
		['brand'] = 'Truffade',
		['model'] = 'thrax',
		['price'] = 480000,
		['category'] = 'super',
		['hash'] = `thrax`,
		['shop'] = 'pdm',
	},
	['tigon'] = {
		['name'] = 'Tigon',
		['brand'] = 'Lampadati',
		['model'] = 'tigon',
		['price'] = 200000,
		['category'] = 'super',
		['hash'] = `tigon`,
		['shop'] = 'pdm',
	},
	['turismor'] = {
		['name'] = 'Turismo R',
		['brand'] = 'Grotti',
		['model'] = 'turismor',
		['price'] = 340000,
		['category'] = 'super',
		['hash'] = `turismor`,
		['shop'] = 'pdm',
	},
	['tyrant'] = {
		['name'] = 'Tyrant',
		['brand'] = ' Överflöd',
		['model'] = 'tyrant',
		['price'] = 420000,
		['category'] = 'super',
		['hash'] = `tyrant`,
		['shop'] = 'pdm',
	},
	['vacca'] = {
		['name'] = 'Vacca',
		['brand'] = 'Pegassi',
		['model'] = 'vacca',
		['price'] = 180000,
		['category'] = 'super',
		['hash'] = `vacca`,
		['shop'] = 'pdm',
	},
	['vagner'] = {
		['name'] = 'Vagner',
		['brand'] = 'Dewbauchee',
		['model'] = 'vagner',
		['price'] = 500000,
		['category'] = 'super',
		['hash'] = `vagner`,
		['shop'] = 'pdm',
	},
	['voltic'] = {
		['name'] = 'Voltic',
		['brand'] = 'Coil',
		['model'] = 'voltic',
		['price'] = 160000,
		['category'] = 'super',
		['hash'] = `voltic`,
		['shop'] = 'pdm',
	},
	['xa21'] = {
		['name'] = 'XA-21',
		['brand'] = 'Ocelot',
		['model'] = 'xa21',
		['price'] = 200000,
		['category'] = 'super',
		['hash'] = `xa21`,
		['shop'] = 'pdm',
	},
	['zentorno'] = {
		['name'] = 'Zentorno',
		['brand'] = 'Pegassi',
		['model'] = 'zentorno',
		['price'] = 540000,
		['category'] = 'super',
		['hash'] = `zentorno`,
		['shop'] = 'pdm',
	},
	['zorrusso'] = {							--DLC
		['name'] = 'Zorrusso',
		['brand'] = 'Pegassi',
		['model'] = 'zorrusso',
		['price'] = 300000,
		['category'] = 'super',
		['hash'] = `zorrusso`,
		['shop'] = 'pdm',
	},
	['ignus'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Ignus',
		['brand'] = 'Pegassi',
		['model'] = 'ignus',
		['price'] = 1050000,
		['category'] = 'super',
		['hash'] = `ignus`,
		['shop'] = 'pdm',
	},
	['zeno'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Zeno',
		['brand'] = 'Overflod',
		['model'] = 'zeno',
		['price'] = 450000,
		['category'] = 'super',
		['hash'] = `zeno`,
		['shop'] = 'pdm',
	},
	
	--// Vans
	
	['bison'] = {
		['name'] = 'Bison',
		['brand'] = 'Bravado',
		['model'] = 'bison',
		['price'] = 50000,
		['category'] = 'vans',
		['hash'] = `bison`,
		['shop'] = 'pdm',
	},
	['bobcatxl'] = {
		['name'] = 'Bobcat XL Open',
		['brand'] = 'Vapid',
		['model'] = 'bobcatxl',
		['price'] = 40000,
		['category'] = 'vans',
		['hash'] = `bobcatxl`,
		['shop'] = 'pdm',
	},
	['burrito3'] = {
		['name'] = 'Burrito',
		['brand'] = 'Declasse',
		['model'] = 'burrito3',
		['price'] = 40000,
		['category'] = 'vans',
		['hash'] = `burrito3`,
		['shop'] = 'pdm',
	},
	['gburrito2'] = {
		['name'] = 'Burrito Custom',
		['brand'] = 'Declasse',
		['model'] = 'gburrito2',
		['price'] = 65000,
		['category'] = 'vans',
		['hash'] = `gburrito2`,
		['shop'] = 'pdm',
	},
	['gburrito'] = {
		['name'] = 'Gang Burrito',
		['brand'] = 'Declasse',
		['model'] = 'gburrito',
		['price'] = 75000,
		['category'] = 'vans',
		['hash'] = `gburrito`,
		['shop'] = 'pdm',
	},
    ['speedo4'] = {
		['name'] = 'Speedo Custom',
		['brand'] = 'Vapid',
		['model'] = 'speedo4',
		['price'] = 45000,
		['category'] = 'vans',
		['hash'] = `speedo4`,
		['shop'] = 'pdm',
	},
	['youga4'] = { 	 	--DLC +set sv_enforceGameBuild 2545
		['name'] = 'Youga',
		['brand'] = 'Bravado',
		['model'] = 'youga4',
		['price'] = 65000,
		['category'] = 'vans',
		['hash'] = `youga4`,
		['shop'] = 'pdm',
	},
	['moonbeam'] = {
		['name'] = 'Moonbeam',
		['brand'] = 'Declasse',
		['model'] = 'moonbeam',
		['price'] = 80000,
		['category'] = 'vans',
		['hash'] = `moonbeam`,
		['shop'] = 'pdm',
	},
	['moonbeam2'] = {
		['name'] = 'Moonbeam Custom',
		['brand'] = 'Declasse',
		['model'] = 'moonbeam2',
		['price'] = 100000,
		['category'] = 'vans',
		['hash'] = `moonbeam2`,
		['shop'] = 'pdm',
	},
	
	--// Boats
	
	['squalo'] = {
		['name'] = 'Squalo',
		['brand'] = 'Shitzu',
		['model'] = 'squalo',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `squalo`,
		['shop'] = 'boats',
	},
	['marquis'] = {
		['name'] = 'Marquis',
		['brand'] = 'Dinka',
		['model'] = 'marquis',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `marquis`,
		['shop'] = 'boats',
	},
	['seashark'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark`,
		['shop'] = 'boats',
	},
	['seashark2'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark2`,
		['shop'] = 'boats',
	},
	['seashark3'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark3',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark3`,
		['shop'] = 'boats',
	},
	['jetmax'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Jetmax',
		['model'] = 'jetmax',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `jetmax`,
		['shop'] = 'boats',
	},
	['tropic'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Tropic',
		['model'] = 'tropic',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `tropic`,
		['shop'] = 'boats',
	},
	['tropic2'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Tropic',
		['model'] = 'tropic2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `tropic2`,
		['shop'] = 'boats',
	},
	['dinghy'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy`,
		['shop'] = 'boats',
	},
	['dinghy2'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy2`,
		['shop'] = 'boats',
	},
	['dinghy3'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy3',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy3`,
		['shop'] = 'boats',
	},
	['dinghy4'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy4',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy4`,
		['shop'] = 'boats',
	},
	['suntrap'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Suntrap',
		['model'] = 'suntrap',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `suntrap`,
		['shop'] = 'boats',
	},
	['speeder'] = {
		['name'] = 'Speeder',
		['brand'] = 'Pegassi',
		['model'] = 'speeder',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `speeder`,
		['shop'] = 'boats',
	},
	['speeder2'] = {
		['name'] = 'Speeder',
		['brand'] = 'Pegassi',
		['model'] = 'speeder2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `speeder2`,
		['shop'] = 'boats',
	},
	['longfin'] = {
		['name'] = 'Longfin',
		['brand'] = 'Shitzu',
		['model'] = 'longfin',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `longfin`,
		['shop'] = 'boats',
	},
	['toro'] = {
		['name'] = 'Toro',
		['brand'] = 'Lampadati',
		['model'] = 'toro',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `toro`,
		['shop'] = 'boats',
	},
	['toro2'] = {
		['name'] = 'Toro',
		['brand'] = 'Lampadati',
		['model'] = 'toro2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `toro2`,
		['shop'] = 'boats',
	},
	-- helicopters
	['buzzard2'] = {
		['name'] = 'Buzzard',
		['brand'] = 'Unknown',
		['model'] = 'buzzard2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `buzzard2`,
		['shop'] = 'air',
	},
	['frogger'] = {
		['name'] = 'Frogger',
		['brand'] = 'Unknown',
		['model'] = 'frogger',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `frogger`,
		['shop'] = 'air',
	},
	['frogger2'] = {
		['name'] = 'Frogger',
		['brand'] = 'Unknown',
		['model'] = 'frogger2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `frogger2`,
		['shop'] = 'air',
	},
	['maverick'] = {
		['name'] = 'Maverick',
		['brand'] = 'Unknown',
		['model'] = 'maverick',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `maverick`,
		['shop'] = 'air',
	},
	['swift'] = {
		['name'] = 'Swift',
		['brand'] = 'Buckingham',
		['model'] = 'swift',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `swift`,
		['shop'] = 'air',
	},
	['swift2'] = {
		['name'] = 'Swift',
		['brand'] = 'Buckingham',
		['model'] = 'swift2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `swift2`,
		['shop'] = 'air',
	},
	['seasparrow'] = {
		['name'] = 'Sea Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow`,
		['shop'] = 'air',
	},
	['seasparrow2'] = {
		['name'] = 'Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow2`,
		['shop'] = 'air',
	},
	['seasparrow3'] = {
		['name'] = 'Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow3',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow3`,
		['shop'] = 'air',
	},
	['supervolito'] = {
		['name'] = 'SuperVolito',
		['brand'] = 'Buckingham',
		['model'] = 'supervolito',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `supervolito`,
		['shop'] = 'air',
	},
	['supervolito2'] = {
		['name'] = 'SuperVolito Carbon',
		['brand'] = 'Buckingham',
		['model'] = 'supervolito2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `supervolito2`,
		['shop'] = 'air',
	},
	['volatus'] = {
		['name'] = 'Volatus',
		['brand'] = 'Buckingham',
		['model'] = 'volatus',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `volatus`,
		['shop'] = 'air',
	},
	['havok'] = {
		['name'] = 'Havok',
		['brand'] = 'Nagasaki',
		['model'] = 'havok',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `havok`,
		['shop'] = 'air',
	},
	-- Planes
	['duster'] = {
		['name'] = 'Duster',
		['brand'] = 'Unknown',
		['model'] = 'duster',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `duster`,
		['shop'] = 'air',
	},
	['luxor'] = {
		['name'] = 'Luxor',
		['brand'] = 'Buckingham',
		['model'] = 'luxor',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `luxor`,
		['shop'] = 'air',
	},
	['luxor2'] = {
		['name'] = 'Luxor Deluxe',
		['brand'] = 'Buckingham',
		['model'] = 'luxor2',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `luxor2`,
		['shop'] = 'air',
	},
	['stunt'] = {
		['name'] = 'Mallard',
		['brand'] = 'Unknown',
		['model'] = 'stunt',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `stunt`,
		['shop'] = 'air',
	},
	['mammatus'] = {
		['name'] = 'Mammatus',
		['brand'] = 'Unknown',
		['model'] = 'mammatus',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `mammatus`,
		['shop'] = 'air',
	},
	['velum'] = {
		['name'] = 'Velum',
		['brand'] = 'Unknown',
		['model'] = 'velum',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `velum`,
		['shop'] = 'air',
	},
	['velum2'] = {
		['name'] = 'Velum',
		['brand'] = 'Unknown',
		['model'] = 'velum2',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `velum2`,
		['shop'] = 'air',
	},
	['shamal'] = {
		['name'] = 'Shamal',
		['brand'] = 'Buckingham',
		['model'] = 'shamal',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `shamal`,
		['shop'] = 'air',
	},
	['vestra'] = {
		['name'] = 'Vestra',
		['brand'] = 'Buckingham',
		['model'] = 'vestra',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `vestra`,
		['shop'] = 'air',
	},
	['dodo'] = {
		['name'] = 'Dodo',
		['brand'] = 'Mammoth',
		['model'] = 'dodo',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `dodo`,
		['shop'] = 'air',
	},
	['howard'] = {
		['name'] = 'Howard NX-25',
		['brand'] = 'Buckingham',
		['model'] = 'howard',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `howard`,
		['shop'] = 'air',
	},
	['alphaz1'] = {
		['name'] = 'Alpha-Z1',
		['brand'] = 'Buckingham',
		['model'] = 'alphaz1',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `alphaz1`,
		['shop'] = 'air',
	},
	['nimbus'] = {
		['name'] = 'Nimbus',
		['brand'] = 'Buckingham',
		['model'] = 'nimbus',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `nimbus`,
		['shop'] = 'air',
	},

-- Police Vehicles

	['npolchal'] = {
        ['name'] = 'Challenger',
        ['brand'] = 'Dodge',
        ['model'] = 'npolchal',
        ['price'] = 1,
        ['category'] = 'emergency',
        ['hash'] = `npolchal`,
        ['shop'] = 'police',
		['slot'] = '5',
		['weight'] = '10000', ---100 = 1 kg
    },
    ['npolstang'] = {
        ['name'] = 'Mustang',
        ['brand'] = 'Ford',
        ['model'] = 'npolstang',
        ['price'] = 1,
        ['category'] = 'emergency',
        ['hash'] = `npolstang`,
        ['shop'] = 'police',
		['slot'] = '5',
		['weight'] = '10000', ---100 = 1 kg
    },
    ['npolvette'] = {
        ['name'] = 'Corvette',
        ['brand'] = 'Chevrolet',
        ['model'] = 'npolvette',
        ['price'] = 1,
        ['category'] = 'emergency',
        ['hash'] = `npolvette`,
        ['shop'] = 'police',
		['slot'] = '5',
		['weight'] = '10000', ---100 = 1 kg
    },
    ['npolvic'] = {
        ['name'] = 'Crown Vic',
        ['brand'] = 'Ford',
        ['model'] = 'npolvic',
        ['price'] = 1,
        ['category'] = 'emergency',
        ['hash'] = `npolvic`,
        ['shop'] = 'police',
		['slot'] = '5',
		['weight'] = '10000', ---100 = 1 kg
    },
    ['npolexp'] = {
        ['name'] = 'Explorer',
        ['brand'] = 'Ford',
        ['model'] = 'npolexp',
        ['price'] = 1,
        ['category'] = 'emergency',
        ['hash'] = `npolexp`,
        ['shop'] = 'police',
		['slot'] = '5',
		['weight'] = '10000', ---100 = 1 kg
    },
    ['npolchar'] = {
        ['name'] = 'Charger',
        ['brand'] = 'Dodge',
        ['model'] = 'npolchar',
        ['price'] = 1,
        ['category'] = 'emergency',
        ['hash'] = `npolchar`,
        ['shop'] = 'police',
		['slot'] = '5',
		['weight'] = '10000', ---100 = 1 kg
    },
	['camaroRB'] = {
        ['name'] = 'Camaro',
        ['brand'] = 'Chevrolet',
        ['model'] = 'camaroRB',
        ['price'] = 1,
        ['category'] = 'emergency',
        ['hash'] = `camaroRB`,
        ['shop'] = 'police',
		['slot'] = '6',
		['weight'] = '100000', ---100 = 1 kg
    },	
}

for k,v in pairs(QBShared.Vehicles) do
	QBShared.VehicleHashes[v.hash] = v
end